---
title: "Class 6 Homework"
author: "Sharon Chang"
date: "4/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Original Code
```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

## Rewritten Code
```{r}
library(bio3d)
kinase_list <- c("4AKE", "1AKE", "1E4Y") # defines the kinases we are analyzing into a vector
bfactor <- function(k) {
  for (k in kinase_list) { # loops over each value in our kinase list vector
  x <- read.pdb(k) # reads the pdb file for each value in our kinase list vector
  x.chainA <- trim.pdb(x, chain = "A", elety = "CA")
  x.b <- x.chainA$atom$b
  plotb3(x.b, sse = x.chainA, typ = "l", ylab = "Bfactor")
  }
}
bfactor(kinase_list) # run the bfactor function with our kinase list values
```

