---
title: 'Class 6: R Functions'
author: "Sharon Chang"
date: "4/18/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### About 
This is my **class 6** r markdown document with my code and notes for the day.

```{r}
plot(1:10, typ='l', col="blue")
```

```{r}
read.csv("test1.txt", header = TRUE, sep=",")
```

```{r}
read.table("test2.txt", header = FALSE, sep = "$")
```

```{r}
read.table("test3.txt", header = FALSE)
```



## Functions

Our first silly function example:

```{r}
add <- function(x, y=1){
  # The body!!
  x + y
}

add(x=1, y=4)
add(1,4)
add(1)

add( c(1,2,3))
add( c(1,2,3),4)

#add(1,2,2)
#add(x=1, y="b")
```

```{r}
rescale <- function(x) {
rng <-range(x)
(x - rng[1]) / (rng[2] - rng[1])
}
```
```{r}
rescale(1:10)
```

```{r}
rescale (1:10)
```
```{r}
x <- c(1,2,NA,3,10)
rng <- range(x, na.rm = TRUE)
rng
(x - rng[1]) / (rng[2] - rng[1])
```

```{r}
rescale2 <- function(x, na.rm=TRUE){
  if(!is.numeric(x))
    print("Give only numbers please")
  rng <- range(x, na.rm = TRUE)
  (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale2 (c(1,3,NA,10))
```

```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
  
  rng <- range(x, na.rm=na.rm) 
  print("Hello")
answer <- (x - rng[1]) / (rng[2] - rng[1])
  

print("is it me you are looking for?")

if(plot) {
plot(answer, typ="b", lwd=4)
  print("Please don't sing again")
}
print("I can see it in ...")
return(answer)
}
```

```{r}
rescale3 (c(1,3,NA,10))
```

